DELETE http://localhost:3002/api/blogs/68c12669dbe5783ae9e5e689
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFub3RoZXJVc2VyIiwiaWQiOiI2OGMxMjZiMmRiZTU3ODNhZTllNWU2OGYiLCJpYXQiOjE3NTc0ODg4NTV9.ILKThQFUZ1RrJRk5MkUAYGuqvI53pmhUttX8D0ticE0